# Generated by Django 5.0.2 on 2024-02-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_items',
        ),
    ]
