# Generated by Django 5.0.2 on 2024-02-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_restaurant_menu_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='FoodItem',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='menu_items',
            new_name='food_items',
        ),
    ]
