# Generated by Django 5.0.2 on 2024-02-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_menuitem_fooditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
